### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by whx123123** [Auromix/isaac_sim_curobo_motion_generator#1]
CUDA:11.8
python:3.10
isaac sim4.0.0
pytorch 2.2.1

I encountered an error after running the command cd isaac_sim_motion_generator followed by omni_python -m pip install -e  .I'd like to ask about your environment configuration and how to resolve this issue.

ERROR: Command errored out with exit status 1:
     command: /home/hiteam/.local/share/ov/pkg/isaac-sim-4.0.0/kit/python/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/opt/isaac_sim_curobo_motion_generator/setup.py'"'"'; __file__='"'"'/opt/isaac_sim_curobo_motion_generator/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-n27d0jsq
         cwd: /opt/isaac_sim_curobo_motion_generator/
    Complete output (1 lines):
    error in isaac_sim_motion_generator setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; 'bool' object is not iterable
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Hermanye996** [comment]
Thank you for reaching out with the issue you encountered during the installation of isaac_sim_motion_generator. Based on the error message you provided, it appears that there is a problem with the install_requires parameter in setup.py file. 


This issue has been resolved in the latest version of the package.
